word_list = [
    "порно", "xvideos", "pornhub", "xnxx", "porn365", "порностудентки", "xhamster", "24video.com", "гейпоревоком", "se× studetki", "порно", "роzzиянам", "отлезали",
    "rule34", "pornez", "pornomoloko", "sexstudentki", "thumbzilla", "pornzog", "erothots", "сломали жизнь", "сука", "бля"
    "thothub", "furry34", "бойкиссер", "насилие", "смертники", "смерти",
    "пленными", "насилие", "оккупантов", "убивать", "жизнью", "хуйово", "кровь", "кровопицы",
    "кровавую", "ахуй", "аху[еий]", "porn",
    "cartoon porn", "teen",
    "shady sites",
    "illegal immigrant",
    "hack",
    "slippery slope",
    "censorship",
    "live-action porn",
    "traffics porn",
    "cult",
    "hack",
    "slippery slope",
    "censorship",
    "written consent",
    "live-action porn",
    "shotgun",
    "porn",
    "suck",
    "horny teenager",
    "earth",
    "sh#tty",
    "f#ckwads",
    "prohibition",
    "fuckgaloo",
    "alcapone",
    "religious senators",
    "enforce","shotgun",
    "porn",
    "american politicians",
    "suck-start a shotgun",
    "horny teenager",
    "earth",
    "sh#tty",
    "f#ckwads",
    "prohibition","CP",
    "electric fuckgaloo",
    "al capone", "fucked",
    "enforce", "dildo",
    "lmao","cum", "hentai", "rape", "riots", "cunts","pair of tits"
]